### ISSUE TITLE
Random Crash for ClupatraAlg

### ISSUE THREAD

**Issue by wenxingfang** [cepc/CEPCSW#94]
We find some times the alg ClupatraAlg will crash

```javascript


 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002b4af26c489e in waitpid () from /lib64/libc.so.6
#1  0x00002b4af26564e9 in do_system () from /lib64/libc.so.6
#2  0x00002b4affb430ba in TUnixSystem::StackTrace() () from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/lib/libCore.so
#3  0x00002b4affb45914 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/lib/libCore.so
#4  <signal handler called>
#5  0x00002b4b1ceb17aa in podio::ObjBase::release (this=0x1a174bf0) at /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.2/podio/include/podio/ObjBase.h:27
#6  podio::ObjBase::release (this=0x1a174bf0) at /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.2/podio/include/podio/ObjBase.h:24
#7  edm4hep::ConstTrackerHit::~ConstTrackerHit (this=<optimized out>, __in_chrg=<optimized out>) at /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.2/EDM4hep-src/edm4hep/src/TrackerHitConst.cc:42
#8  0x00002b4b2e96c288 in std::_Rb_tree<edm4hep::ConstTrackerHit, std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*>, std::_Select1st<std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*> >, std::less<edm4hep::ConstTrackerHit>, std::allocator<std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*> > >::_M_erase(std::_Rb_tree_node<std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*> >*) () from /workfs/higgs/fangwx/fork_TrackerEcal_20201129/CEPCSW/build.97.0.2.x86_64-slc6-gcc8-opt/lib/libTracking.so
#9  0x00002b4b2e96c27b in std::_Rb_tree<edm4hep::ConstTrackerHit, std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*>, std::_Select1st<std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*> >, std::less<edm4hep::ConstTrackerHit>, std::allocator<std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*> > >::_M_erase(std::_Rb_tree_node<std::pair<edm4hep::ConstTrackerHit const, nnclu::Element<clupatra_new::ClupaHit>*> >*) () from /workfs/higgs/fangwx/fork_TrackerEcal_20201129/CEPCSW/build.97.0.2.x86_64-slc6-gcc8-opt/lib/libTracking.so
#10 0x00002b4b2e95c924 in ClupatraAlg::execute() () from /workfs/higgs/fangwx/fork_TrackerEcal_20201129/CEPCSW/build.97.0.2.x86_64-slc6-gcc8-opt/lib/libTracking.so
#11 0x00002b4aff725ced in Gaudi::details::LegacyAlgorithmAdapter::execute(EventContext const&) const () from /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.2/Gaudi/lib/libGaudiCoreSvc.so


```

**Comment by mirguest** [comment]
Hi @wenxingfang ,
Thank you for reporting the problem.
Could you provide the detail script to @zhaomr13 and @fucd for testing?

@zhaomr13 and @fucd, could you check the problem? Thank you!

Tao

**Comment by wenxingfang** [comment]
Hi @mirguest ,

Actually, I have reported this bug to @fucd. After that @zoujh found the reason and create a pull request #93 for solving this bug.

Best,
Wenxing

**Comment by mirguest** [comment]
Hi @zoujh and @wenxingfang ,
Could you explain a bit more? It would be useful for other people during the migration of algorithms. Thank you!
Tao

**Comment by wenxingfang** [comment]
Hi @mirguest,
 
For my understanding, we should release object in the same event not in next event which may cause break because some of these objects already have been released  by framework. I had same experience when I migrating the pandora. This is easy to make the mistake but hard to find.

Best,
Wenxing
